/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "can.h"
#include "i2c.h"
#include "iwdg.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "data_t26.h"   // Generated by cantools from DBC (AQT2 message, etc.)

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
// CAN fault must last this long before CAN1 is fully restarted (ABOM normally clears bus-off in a few ms)
#define CAN_RECOVER_MS  200
#define CAN_DEBUG_ITS   (CAN_IT_TX_MAILBOX_EMPTY | CAN_IT_ERROR_WARNING | CAN_IT_ERROR_PASSIVE | \
                         CAN_IT_BUSOFF | CAN_IT_LAST_ERROR_CODE | CAN_IT_ERROR)

// MLX90641 16x12 IR array on I2C3 (PA8 SCL / PC9 SDA)
#define MLX_ADDR        (0x33 << 1)   // default 7-bit slave address 0x33 (HAL wants it shifted)
#define MLX_RATE        3             // 0x800D bits 9:7: 2 = 2 Hz, 3 = 4 Hz, 4 = 8 Hz (every subpage is a full 16x12 frame)
#define EE(a)           mlx_ee[(a) - 0x2400]

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */
volatile uint32_t time_ms = 0;

// CAN
CAN_TxHeaderTypeDef TxHeader;
uint8_t TxData[8];
uint32_t TxMailbox;

// --- WHEEL SPEED SENSORS CONFIGURATION ---
typedef struct {
    volatile uint16_t last_capture;     // Store timer reading from previous tooth
    volatile uint16_t delta_counts;    // Time interval between 2 teeth (in microseconds)
    volatile float rpm;                 // Calculated speed in RPM
    volatile uint8_t first_capture;     // Flag to ignore first pulse at startup
    volatile uint32_t last_pulse_ms;    // Timestamp (in ms) of the last detected tooth
} WheelSensor;

// Instances for Wheel Sensors
WheelSensor sensor_wheel_1 = {0, 0, 0.0f, 1, 0}; // Connected to PB0 (TIM3_CH3)
WheelSensor sensor_wheel_2 = {0, 0, 0.0f, 1, 0}; // Connected to PB1 (TIM3_CH4)

// --- DEBUG SNAPSHOT (add "debug" to Live Expressions) ---
typedef struct {
    uint32_t time_ms;
    uint8_t  iwdg_reset;            // 1 = last reset was caused by the watchdog
    struct {
        float    rpm;
        uint16_t delta_counts;
        uint32_t last_pulse_ms;
    } wheel[2];                     // [0] = sensor_wheel_1 (PB0), [1] = sensor_wheel_2 (PB1)
    struct {
        uint32_t tx_queued;         // HAL_CAN_AddTxMessage OK
        uint32_t tx_queue_fail;     // HAL_CAN_AddTxMessage failed (no free mailbox / not started)
        uint32_t tx_ok;             // frame ACKed on the bus
        uint32_t err_count;         // HAL_CAN_ErrorCallback hits
        uint32_t recover_count;     // CAN1 restarts done by can_watchdog()
        uint32_t last_error;        // HAL_CAN_ERROR_* bits of the latest error (0x20 ACK, 0x08 stuff, 0x10 form,
                                    // 0x40/0x80 bit rec/dom, 0x100 CRC, 0x04 bus-off, 0x1000 TX_TERR0...)
        uint32_t error_flags;       // every HAL_CAN_ERROR_* bit seen since boot
        uint8_t  tec;               // transmit error counter (>=128 passive, >255 bus-off)
        uint8_t  rec;               // receive error counter
        uint8_t  bus_off;
        uint8_t  error_passive;
        uint8_t  error_warning;
        uint8_t  free_mailboxes;    // 0..3
        uint8_t  state;             // HAL_CAN_StateTypeDef (2 = LISTENING = running)
        uint8_t  last_tx[8];        // payload of the last queued frame
    } can;
} DebugData;

volatile DebugData debug;

// --- MLX90641 (add "mlx" to Live Expressions) ---
typedef struct {
    float    to[12][16];    // object temperature in degC, [row][col] = datasheet Pix(row+1, col+1)
    float    ta;            // sensor package temperature (degC)
    float    vdd;           // sensor supply (V)
    uint32_t frames;        // frames computed (one per subpage)
    uint32_t i2c_err;       // failed I2C transfers
    uint8_t  ready;         // EEPROM read + refresh rate set
    uint8_t  subpage;       // subpage of the last frame
} MLX90641;

MLX90641 mlx;
static uint16_t mlx_ee[832];    // calibration EEPROM 0x2400..0x273F, read once

// Tasks Prototypes
void execute_immediate_tasks(void);
void execute_10ms_tasks(void);
void execute_50ms_tasks(void);
void execute_100ms_tasks(void);

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */

float MeasureWheelRPM(uint16_t delta_us);

int _write(int file, char *data, int len) {
    HAL_UART_Transmit(&huart1, (uint8_t*) data, len, HAL_MAX_DELAY);
    return len;
}

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef* htim){
    if (htim->Instance == TIM7) {
        time_ms++;
    }
}

// Hardware Capture Interrupt: Triggered automatically on rising edges (PB0 & PB1)
void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim) {
    if (htim->Instance == TIM3) {

        // --- SENSOR 1: PB0 (TIM3 Channel 3) ---
        if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_3) {
            uint16_t current_capture = HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_3);

            if (!sensor_wheel_1.first_capture) {
                // 16-bit subtraction handles counter overflow (65535 -> 0) automatically
                sensor_wheel_1.delta_counts = (uint16_t)(current_capture - sensor_wheel_1.last_capture);

                if (sensor_wheel_1.delta_counts > 0) {
                    sensor_wheel_1.rpm = MeasureWheelRPM(sensor_wheel_1.delta_counts);
                    sensor_wheel_1.last_pulse_ms = time_ms; // Save timestamp of last pulse
                }
            } else {
                sensor_wheel_1.first_capture = 0;
            }
            sensor_wheel_1.last_capture = current_capture;
        }

        // --- SENSOR 2: PB1 (TIM3 Channel 4) ---
        if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_4) {
            uint16_t current_capture = HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_4);

            if (!sensor_wheel_2.first_capture) {
                sensor_wheel_2.delta_counts = (uint16_t)(current_capture - sensor_wheel_2.last_capture);

                if (sensor_wheel_2.delta_counts > 0) {
                    sensor_wheel_2.rpm = MeasureWheelRPM(sensor_wheel_2.delta_counts);
                    sensor_wheel_2.last_pulse_ms = time_ms; // Save timestamp of last pulse
                }
            } else {
                sensor_wheel_2.first_capture = 0;
            }
            sensor_wheel_2.last_capture = current_capture;
        }
    }
}

// CAN debug callbacks (need HAL_CAN_ActivateNotification in main)
void HAL_CAN_TxMailbox0CompleteCallback(CAN_HandleTypeDef *hcan) { debug.can.tx_ok++; }
void HAL_CAN_TxMailbox1CompleteCallback(CAN_HandleTypeDef *hcan) { debug.can.tx_ok++; }
void HAL_CAN_TxMailbox2CompleteCallback(CAN_HandleTypeDef *hcan) { debug.can.tx_ok++; }

void HAL_CAN_ErrorCallback(CAN_HandleTypeDef *hcan) {
    debug.can.err_count++;
    debug.can.last_error = hcan->ErrorCode;
    debug.can.error_flags |= hcan->ErrorCode;
    HAL_CAN_ResetError(hcan);
}
/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_CAN1_Init();
  MX_USART1_UART_Init();
  MX_TIM7_Init();
  MX_IWDG_Init();
  MX_TIM3_Init();
  MX_I2C3_Init();
  /* USER CODE BEGIN 2 */
  HAL_TIM_Base_Start_IT(&htim7);

  // Start Input Capture for both wheel speed sensors
  HAL_TIM_IC_Start_IT(&htim3, TIM_CHANNEL_3); // PB0
  HAL_TIM_IC_Start_IT(&htim3, TIM_CHANNEL_4); // PB1

  // Debug: TX-complete + error interrupts feed debug.can
  HAL_CAN_ActivateNotification(&hcan1, CAN_DEBUG_ITS);

  debug.iwdg_reset = __HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST);
  __HAL_RCC_CLEAR_RESET_FLAGS();

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
    while (1) {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */

        // Execute immediate tasks
        execute_immediate_tasks();

        static uint32_t previus_tick_10ms = 0;
        static uint32_t previus_tick_50ms = 0;
        static uint32_t previus_tick_100ms = 0;

        // Execute 10ms Tasks
        if (time_ms - previus_tick_10ms >= 10) {
            execute_10ms_tasks();
            previus_tick_10ms = time_ms;
        }

        // Execute 50ms Tasks
        if (time_ms - previus_tick_50ms >= 50) {
            execute_50ms_tasks();
            previus_tick_50ms = time_ms;
        }

        // Execute 100ms Tasks
        if (time_ms - previus_tick_100ms >= 100) {
            execute_100ms_tasks();
            previus_tick_100ms = time_ms;
        }
    }

  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_LSI|RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.LSIState = RCC_LSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 4;
  RCC_OscInitStruct.PLL.PLLN = 96;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = 2;
  RCC_OscInitStruct.PLL.PLLR = 2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */
void execute_immediate_tasks() {

}

// Copy current state into the debug struct (ISR counters are updated in the callbacks)
static void debug_update(void) {
    debug.time_ms = time_ms;

    debug.wheel[0].rpm           = sensor_wheel_1.rpm;
    debug.wheel[0].delta_counts  = sensor_wheel_1.delta_counts;
    debug.wheel[0].last_pulse_ms = sensor_wheel_1.last_pulse_ms;
    debug.wheel[1].rpm           = sensor_wheel_2.rpm;
    debug.wheel[1].delta_counts  = sensor_wheel_2.delta_counts;
    debug.wheel[1].last_pulse_ms = sensor_wheel_2.last_pulse_ms;

    uint32_t esr = hcan1.Instance->ESR;
    debug.can.tec            = (esr & CAN_ESR_TEC) >> CAN_ESR_TEC_Pos;
    debug.can.rec            = (esr & CAN_ESR_REC) >> CAN_ESR_REC_Pos;
    debug.can.bus_off        = (esr & CAN_ESR_BOFF) != 0;
    debug.can.error_passive  = (esr & CAN_ESR_EPVF) != 0;
    debug.can.error_warning  = (esr & CAN_ESR_EWGF) != 0;
    debug.can.free_mailboxes = HAL_CAN_GetTxMailboxesFreeLevel(&hcan1);
    debug.can.state          = HAL_CAN_GetState(&hcan1);
}

// CAN1 watchdog: if the peripheral is not running (Start timed out), stays bus-off
// (hardware ABOM didn't recover) or has all 3 TX mailboxes stuck for CAN_RECOVER_MS,
// restart it from scratch. Keeps retrying every CAN_RECOVER_MS until healthy.
static void can_watchdog(void) {
    static uint32_t last_healthy_ms = 0;

    uint8_t healthy = HAL_CAN_GetState(&hcan1) == HAL_CAN_STATE_LISTENING
                   && !(hcan1.Instance->ESR & CAN_ESR_BOFF)
                   && HAL_CAN_GetTxMailboxesFreeLevel(&hcan1) > 0;

    if (healthy) {
        last_healthy_ms = time_ms;
        return;
    }
    if (time_ms - last_healthy_ms < CAN_RECOVER_MS) {
        return;
    }

    HAL_CAN_DeInit(&hcan1);          // IRQs + clock off, HAL state -> RESET
    __HAL_RCC_CAN1_FORCE_RESET();    // real peripheral reset: DeInit writes MCR_RESET with the clock already off
    __HAL_RCC_CAN1_RELEASE_RESET();
    MX_CAN1_Init();                  // init + filter + start (blocks <= ~30 ms, IWDG is 2 s)
    HAL_CAN_ActivateNotification(&hcan1, CAN_DEBUG_ITS);

    debug.can.recover_count++;
    last_healthy_ms = time_ms;       // next attempt only after another CAN_RECOVER_MS
}

// ---------------- MLX90641 (datasheet sections 10-11) ----------------
// Words are big-endian on the bus -> swap after reading
static HAL_StatusTypeDef mlx_read(uint16_t addr, uint16_t *buf, uint16_t words) {
    HAL_StatusTypeDef st = HAL_I2C_Mem_Read(&hi2c3, MLX_ADDR, addr, I2C_MEMADD_SIZE_16BIT, (uint8_t *)buf, words * 2, 100);
    for (uint16_t i = 0; i < words; i++) buf[i] = __REV16(buf[i]);
    if (st != HAL_OK) mlx.i2c_err++;
    return st;
}

static HAL_StatusTypeDef mlx_write(uint16_t addr, uint16_t val) {
    uint8_t b[2] = { val >> 8, val & 0xFF };
    HAL_StatusTypeDef st = HAL_I2C_Mem_Write(&hi2c3, MLX_ADDR, addr, I2C_MEMADD_SIZE_16BIT, b, 2, 100);
    if (st != HAL_OK) mlx.i2c_err++;
    return st;
}

// Two's complement of the low `bits` of v (EEPROM words carry 5 Hamming bits on top, ignored)
static int32_t sext(uint32_t v, int bits) {
    v &= (1u << bits) - 1;
    return v >= (1u << (bits - 1)) ? (int32_t)v - (1 << bits) : (int32_t)v;
}

// Raw subpage -> mlx.to[][] (section 11.2.2). pix = 192 pixels in pixel order, aux = RAM 0x0580..0x05AF.
// ADC resolution is left at the calibrated value, so Resolution_corr = 1.
static void mlx_calc(const uint16_t *pix, const uint16_t *aux, int sp) {
    // 11.2.2.2 Vdd
    float kvdd  = sext(EE(0x2427), 11) * 32.0f;
    float vdd25 = sext(EE(0x2426), 11) * 32.0f;
    float dv    = ((int16_t)aux[0x2A] - vdd25) / kvdd;                     // Vdd - 3.3 V (RAM 0x05AA)

    // 11.2.2.3 Ta
    float kvptat  = sext(EE(0x242B), 11) / 4096.0f;
    float ktptat  = sext(EE(0x242A), 11) / 8.0f;
    float vptat25 = 32.0f * (EE(0x2428) & 0x7FF) + (EE(0x2429) & 0x7FF);
    float aptat   = (EE(0x242C) & 0x7FF) / 128.0f;
    float vptat   = (int16_t)aux[0x20];                                    // RAM 0x05A0
    float vbe     = (int16_t)aux[0x00];                                    // RAM 0x0580
    float vart    = vptat / (vptat * aptat + vbe) * 262144.0f;
    float ta      = (vart / (1 + kvptat * dv) - vptat25) / ktptat + 25;

    // 11.2.2.4 gain, 11.2.2.6 compensation pixel, 11.2.2.7 TGC, emissivity, KsTa
    float kgain   = (32.0f * (EE(0x2424) & 0x7FF) + (EE(0x2425) & 0x7FF)) / (int16_t)aux[0x0A];   // RAM 0x058A
    float cpkta   = ldexpf(sext(EE(0x2431), 6), -((EE(0x2431) & 0x7C0) >> 6));
    float cpkv    = ldexpf(sext(EE(0x2432), 6), -((EE(0x2432) & 0x7C0) >> 6));
    float cpos    = sext(32 * (EE(0x242F) & 0x7FF) + (EE(0x2430) & 0x7FF), 16);
    float cp      = (int16_t)aux[sp ? 0x28 : 0x08] * kgain                 // RAM 0x05A8 (SP1) / 0x0588 (SP0)
                  - cpos * (1 + cpkta * (ta - 25)) * (1 + cpkv * dv);
    float alphacp = ldexpf(EE(0x242D) & 0x7FF, -(EE(0x242E) & 0x7FF));
    float tgc     = sext(EE(0x2433), 9) / 64.0f;
    float emis    = sext(EE(0x2423), 11) / 512.0f;
    float ksta    = sext(EE(0x2422), 11) / 32768.0f;

    // 11.1.9-11.1.11 temperature ranges: corner temps, KsTo, alpha correction
    static const uint16_t ksto_ee[8] = { 0x2435, 0x2436, 0x2437, 0x2438, 0x2439, 0x243B, 0x243D, 0x243F };
    float ct[8] = { -40, -20, 0, 80, 120, EE(0x243A) & 0x7FF, EE(0x243C) & 0x7FF, EE(0x243E) & 0x7FF };
    float ksto[8], acorr[8];
    for (int i = 0; i < 8; i++) ksto[i] = ldexpf(sext(EE(ksto_ee[i]), 11), -(EE(0x2434) & 0x7FF));
    acorr[2] = 1;
    acorr[1] = 1 / (1 + ksto[1] * (ct[2] - ct[1]));
    acorr[0] = acorr[1] / (1 + ksto[0] * (ct[1] - ct[0]));
    for (int i = 3; i < 8; i++) acorr[i] = acorr[i - 1] * (1 + ksto[i - 1] * (ct[i] - ct[i - 1]));

    // 11.2.2.9 reflected temperature unknown -> Tr = Ta - 5
    float tak4 = powf(ta + 273.15f, 4), trk4 = powf(ta - 5 + 273.15f, 4);
    float tar  = trk4 - (trk4 - tak4) / emis;

    // 11.1.3-11.1.6 offset / Kta / Kv common parts
    float osavg   = sext(32 * (EE(0x2411) & 0x7FF) + (EE(0x2412) & 0x7FF), 16);
    int   osscale = (EE(0x2410) & 0x7E0) >> 5;
    float ktaavg  = sext(EE(0x2415), 11), kvavg = sext(EE(0x2417), 11);
    int   ktas1   = (EE(0x2416) & 0x7E0) >> 5, ktas2 = EE(0x2416) & 0x1F;
    int   kvs1    = (EE(0x2418) & 0x7E0) >> 5, kvs2  = EE(0x2418) & 0x1F;

    for (int n = 0; n < 192; n++) {
        int   g      = n / 32;                                             // alpha reference group = 2 rows
        int   ascale = (g & 1 ? EE(0x2419 + g / 2) & 0x1F : (EE(0x2419 + g / 2) & 0x7E0) >> 5) + 20;
        float alpha  = ldexpf((EE(0x2500 + n) & 0x7FF) / 2047.0f * (EE(0x241C + g) & 0x7FF), -ascale);
        float kta    = ldexpf(ldexpf(sext(EE(0x25C0 + n) >> 5, 6), ktas2) + ktaavg, -ktas1);
        float kv     = ldexpf(ldexpf(sext(EE(0x25C0 + n), 5), kvs2) + kvavg, -kvs1);
        float os     = osavg + ldexpf(sext(EE((sp ? 0x2680 : 0x2440) + n), 11), osscale);

        float vir = (int16_t)pix[n] * kgain - os * (1 + kta * (ta - 25)) * (1 + kv * dv);   // 11.2.2.5
        vir = (vir - tgc * cp) / emis;                                                       // 11.2.2.7
        float ac  = (alpha - tgc * alphacp) * (1 + ksta * (ta - 25));                        // 11.2.2.8

        // 11.2.2.9 To in the basic range, then again with the range it falls in (11.2.2.9.1.3)
        float sx = ksto[2] * sqrtf(sqrtf(ac * ac * ac * vir + ac * ac * ac * ac * tar));
        float to = sqrtf(sqrtf(vir / (ac * (1 - ksto[2] * 273.15f) + sx) + tar)) - 273.15f;
        int r = 0;
        while (r < 7 && to >= ct[r + 1]) r++;
        mlx.to[n / 16][n % 16] = sqrtf(sqrtf(vir / (ac * acorr[r] * (1 + ksto[r] * (to - ct[r]))) + tar)) - 273.15f;
    }
    mlx.ta  = ta;
    mlx.vdd = dv + 3.3f;
}

// Read calibration EEPROM once and set the refresh rate
static HAL_StatusTypeDef mlx_init(void) {
    uint16_t ctrl;
    if (mlx_read(0x2400, mlx_ee, 832) != HAL_OK || mlx_read(0x800D, &ctrl, 1) != HAL_OK) {
        return HAL_ERROR;
    }
    return mlx_write(0x800D, (ctrl & ~0x0380) | (MLX_RATE << 7));
}

// Polled every 10 ms: when a new subpage is in RAM, read it and compute the 16x12 temperatures
static void mlx_task(void) {
    static uint16_t pix[192], aux[48];
    uint16_t status;

    if (!mlx.ready) {   // retries until the sensor answers (datasheet 10.5: wait 80 ms after POR)
        mlx.ready = time_ms > 80 && mlx_init() == HAL_OK;
        return;
    }
    if (mlx_read(0x8000, &status, 1) != HAL_OK || !(status & 0x0008)) {   // bit 3: new data in RAM
        return;
    }

    int sp = status & 1;                                                   // bits 2:0: last measured subpage
    HAL_StatusTypeDef st = HAL_OK;
    for (int k = 0; k < 6; k++) {                                          // rows interleave SP0/SP1 every 32 words (Fig 13)
        st |= mlx_read(0x0400 + k * 0x40 + sp * 0x20, pix + k * 32, 32);
    }
    st |= mlx_read(0x0580, aux, 48);                                       // Vbe, CP, gain, PTAT, Vdd
    st |= mlx_write(0x8000, status & ~0x0008);                             // clear new-data bit
    if (st != HAL_OK) {
        return;
    }

    mlx_calc(pix, aux, sp);
    mlx.subpage = sp;
    mlx.frames++;
}

void execute_10ms_tasks() {
    HAL_IWDG_Refresh(&hiwdg);

    // Standstill Detection: Force 0 RPM if no pulse received in the last 300ms
    if (time_ms - sensor_wheel_1.last_pulse_ms > 300) {
        sensor_wheel_1.rpm = 0.0f;
    }

    if (time_ms - sensor_wheel_2.last_pulse_ms > 300) {
        sensor_wheel_2.rpm = 0.0f;
    }

    can_watchdog();
    mlx_task();
    debug_update();
}

void execute_50ms_tasks() {

    // Assemble the AQT2 message (wheel speed) with the struct/pack generated by cantools
    // from the DBC (data_t26.h). This replaces manual byte packing.
    struct data_t26_aqt2_t aqt2_msg;
    aqt2_msg.front_left_wheel_rpm  = (uint16_t)(sensor_wheel_1.rpm + 0.5f);
    aqt2_msg.front_right_wheel_rpm = (uint16_t)(sensor_wheel_2.rpm + 0.5f);

    // IMPORTANT NOTE: DO NOT use data_t26_aqt2_front_left_wheel_rpm_encode() /
    // _front_right_wheel_rpm_encode() for now. The Factor for both signals in the
    // DBC is set to 0 (shows in yellow in Kvaser DB Editor), which caused cantools to
    // generate "return (uint16_t)(value / 0.0);" - division by zero, undefined
    // behavior. Fix the Factor to 1 for both signals in the DBC, regenerate
    // data_t26.c/h, and only then start using the encode/decode functions.
    // For now, we go directly to pack() with the raw RPM value, which
    // does not depend on encode() and works fine.
    uint8_t aqt2_buf[DATA_T26_AQT2_LENGTH];
    if (data_t26_aqt2_pack(aqt2_buf, &aqt2_msg, sizeof(aqt2_buf)) < 0) {
        Error_Handler();
    }

    // CAN Frame Setup
    TxHeader.IDE = CAN_ID_STD;
    TxHeader.StdId = DATA_T26_AQT2_FRAME_ID;   // 0x720 (AQT2, confirmed in DBC)
    TxHeader.RTR = CAN_RTR_DATA;
    TxHeader.DLC = DATA_T26_AQT2_LENGTH;       // 4

    memcpy(TxData, aqt2_buf, DATA_T26_AQT2_LENGTH);

    // Send Message to CAN Bus (a failed queue is counted, not fatal)
    if (HAL_CAN_AddTxMessage(&hcan1, &TxHeader, TxData, &TxMailbox) == HAL_OK) {
        debug.can.tx_queued++;
        memcpy((void *)debug.can.last_tx, TxData, sizeof(TxData));
    } else {
        debug.can.tx_queue_fail++;
    }

    /*if (HAL_CAN_AddTxMessage(&hcan2, &TxHeader, TxData, &TxMailbox) != HAL_OK) {
        Error_Handler();
    }*/
}

void execute_100ms_tasks() {
    HAL_GPIO_TogglePin(HEARTBEAT_GPIO_Port, HEARTBEAT_Pin); // HEARTBEAT

    // Velocity sensor debug
    printf("Wheel 1: %.1f RPM | Wheel 2: %.1f RPM\r\n", sensor_wheel_1.rpm, sensor_wheel_2.rpm);
}

// Measurements

// Calculates Wheel RPM based on time between teeth (microseconds)
float MeasureWheelRPM(uint16_t delta_us)
{
    const float TIMER_FREQ_HZ = 1000000.0f; // 1 MHz Timer Clock -> 1 us resolution
    const float NUMBER_OF_TEETH = 20.0f;    // Disc teeth count

    if (delta_us == 0) {
        return 0.0f;
    }

    // Formula: RPM = (60 sec * 1,000,000 us) / (20 teeth * delta_us)
    return (60.0f * TIMER_FREQ_HZ) / (NUMBER_OF_TEETH * (float)delta_us);
}
/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
    /* User can add his own implementation to report the HAL error return state */
    __disable_irq();
    while (1) {
    }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
